### ISSUE TITLE
Box Multipart uploads failing.

### ISSUE THREAD

**Issue by lutherism** [Kloudless/kloudless-python#2]
Hello Kloudless,

Recently, our multipart Box uploads started failing, and none go through any more. Is multi part upload still supported on Box?

`account_id: 107009790, folder: FDHwBf6NWdOAVK4u9n0rj2w==,` was a recent failed upload attempt.

Thank you

-Alex

**Comment by vinodc** [comment]
Hi @lutherism . I've followed up via email regarding uploading large files to Box. Since Box does not currently support uploading a file in parts, Kloudless has never included support for this capability. A full list of services that support multipart uploads is available at http://developers.kloudless.com/docs#multipart-upload
